version: '3'
services:
  db:
    container_name: postgresql
    image: postgres:16
    command: -db-ssl-mode=allow
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data
      - ./postgres-custom-config:/etc/postgresql
    env_file:
      - .env
  api:
    container_name: api_backend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SECRET: VIKTORIA_SECRET
    depends_on:
      - db