version: '3'
services:
  db:
    container_name: postgresql
    image: postgres:16
    command: -db-ssl-mode=allow
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data
      - ./postgres-custom-config:/etc/postgresql
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U default_user -d api_database" ]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    container_name: api_backend
    build:
      context: ./
      dockerfile: Project/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./
      dockerfile: frontend/Dockerfile
    ports:
      - "3001:3001"
    restart: always
    depends_on:
      - api

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage: