@startuml
actor Пользователь
actor Администратор
participant Система
participant "Сервер печати" as Server
participant Принтер

Пользователь -> Система : Запрос на печать файла
Система -> Пользователь : Подтверждение запроса
Система -> Server : Обработка и отправка файла
Server -> Принтер : Отправка файла для печати
Принтер -> Server : Уведомление о начале печати
Принтер -> Server : Уведомление о завершении печати
Server -> Система : Уведомление о завершении печати
Система -> Пользователь : Уведомление о завершении печати

Администратор -> Система : Проверка состояния сервиса
Система -> Администратор : Информация о работе сервиса
Система -> Администратор : Уведомления о проблемах
Администратор -> Система : Запрос на печать нераспечатанных файлов
Система -> Администратор : Подтверждение запроса
Система ->  Server : Отправка запроса на печать файла
Server -> Принтер : Отправка файла для печати
Принтер -> Server : Уведомление о начале печати
Принтер -> Server : Уведомление о завершении печати
Server -> Система : Уведомление о завершении печати
Система -> Администратор : Уведомление о завершении печати
@enduml

