@startuml
actor Пользователь
actor Администратор
participant Система
participant "Сервер печати" as Server
participant Принтер

Пользователь -> Система : Отправка данных для регистрации
Система -> Администратор : Отправка данных по новому пользователю
Администратор -> Система : Подтверждение / отклонение регистрации пользователя
Система -> Пользователь : Ответ на запрос регистрации

Пользователь -> Система : Запрос на печать файла
Система -> Пользователь : Подтверждение запроса
Система -> Server : Обработка и отправка файла
Server -> Принтер : Отправка файла для печати
Принтер -> Server : Уведомление о начале печати
Принтер -> Server : Уведомление о завершении печати / об ошибке
Server -> Система : Уведомление о завершении печати / об ошибке
Система -> Пользователь : Уведомление о завершении печати / об ошибке

Администратор -> Система : Отправка данных для регистрации администратора
Система -> Администратор : Ответ на запрос регистрации администратора

Администратор -> Система : Проверка наличия нераспечатанных файлов
Система -> Администратор : Информация о нераспечатанных файлах

Администратор -> Система : Запрос на печать нераспечатанных файлов
Система -> Администратор : Подтверждение запроса
Система ->  Server : Отправка запроса на печать файла
Server -> Принтер : Отправка файла для печати
Принтер -> Server : Уведомление о начале печати
Принтер -> Server : Уведомление о завершении печати / об ошибке
Server -> Система : Уведомление о завершении печати / об ошибке
Система -> Администратор : Уведомление о завершении печати / об ошибке
@enduml
