@startuml
actor Пользователь
actor Администратор
participant "Сервер" as Server
participant "База данных" as db
participant Принтер

Пользователь -> Server : Отправка данных для регистрации
Server -> Администратор : Отправка данных по новому пользователю
Администратор -> Server : Подтверждение / отклонение регистрации пользователя
Server -> db : Запись нового пользователя
Server -> Пользователь : Ответ на запрос регистрации

Пользователь -> Server : Запрос на печать файла
Server -> db : Запись нового файла в бд
Server -> Принтер : Отправка файла для печати
Принтер -> Server : Уведомление о завершении печати / об ошибке
Server -> Пользователь : Уведомление о завершении печати / об ошибке

Пользователь -> Server : Проверка наличия нераспечатанных файлов
Server -> db : Запрос на информацию о нераспечатанных файлах
db -> Server : Информация о нераспечатанных файлах
Server -> Пользователь : Информация о нераспечатанных файлах

Пользователь -> Server : Запрос на печать нераспечатанных файлов
Server -> Принтер : Отправка файла для печати
Принтер -> Server : Уведомление о завершении печати / об ошибке
Server -> Пользователь : Уведомление о завершении печати / об ошибке

Пользователь -> Server : Запрос на получение ранее распечатанных файлов
Server -> db : Запрос на информацию о ранее распечатанных файлах
db -> Server : Информация о ранее распечатанных файлах
Server -> Пользователь : Информация о ранее распечатанных файлах

Администратор -> Server : Отправка данных для регистрации администратора
Server -> db : Запись администратора
Server -> Администратор : Ответ на запрос регистрации администратора

@enduml
