spring:
  application:
    name: printerApplication
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/api_database # сюда нужно вписать url для вашей базы
    username: default_user
    password: qwerty123!
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update