spring:
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, metrics, prometheus

  metrics:
    export:
      prometheus:
        enabled: true